name: slack-channel-specified
on: push

jobs:
  build:
    name: job-success
    runs-on: [self-hosted, "{{.Namespace}}/{{.RunnerPool}}"]
    # Used to verify the Slack channel recorded in runner status.
    env:
      MEOWS_SLACK_CHANNEL: "#test2"
    steps:
      - run: job-started
      - run: meows slackagent set-channel "#test1"
      - run: job-success
