apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-agent
  namespace: meows
spec:
  # Run a single (replicas = 1) slack-agent
  #
  # Multiple replicas (replicas >= 2) open multiple connections.
  # They easily reach the rate limit and the test will be flaky.
  replicas: 1
  template:
    spec:
      containers:
      - name: agent
        image: meows-controller:kindtest
        imagePullPolicy: Never
