name: Pinact
on:
  pull_request:
    paths:
      - ".github/**/*.yaml"
jobs:
  verify-pinact:
    name: Verify pinned GitHub Actions
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/aqua
      - name: Verify SHAs and tag comments are consistent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pinact run --check --verify-comment --min-age 14
