name: Release runner
on:
  pull_request:
    paths:
      - "runner-images/runner.json"
  push:
    branches:
      - "main"
    paths:
      - "runner-images/runner.json"

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  get-released-versions:
    name: Get released versions for runner images
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      meows_version: ${{ steps.versions.outputs.meows_version }}
      runner_version: ${{ steps.versions.outputs.runner_version }}
      runner_sha256: ${{ steps.versions.outputs.runner_sha256 }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Read versions
        id: versions
        run: |
          echo "meows_version=$(cat VERSION)" >> $GITHUB_OUTPUT
          echo "runner_version=$(jq -r .version runner-images/runner.json)" >> $GITHUB_OUTPUT
          echo "runner_sha256=$(jq -r .sha256 runner-images/runner.json)" >> $GITHUB_OUTPUT
  build-and-push-runner-images:
    name: Build and push runner images
    needs: get-released-versions
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-build-and-push-runner-images.yaml
    with:
      meows_version: ${{ needs.get-released-versions.outputs.meows_version }}
      runner_version: ${{ needs.get-released-versions.outputs.runner_version }}
      runner_sha256: ${{ needs.get-released-versions.outputs.runner_sha256 }}
      push_image: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
