name: update runner version
on:
  pull_request:
  push:
    branches:
      - "main"
    paths:
      - "runner-images/RUNNER_VERSION"
jobs:
  get-versions:
    name: Get versions for runner image
    runs-on: ubuntu-24.04
    outputs:
      meows_version: ${{ steps.meows_version.outputs.version }}
      runner_version: ${{ steps.runner_version.outputs.version }}
    steps:
      - uses: actions/checkout@v5
      - name: Get meows version
        id: meows_version
        run: |
          meows_version="$(awk -F'"' '/Version =/ {print $2}' constants.go)"
          echo version=$meows_version >> $GITHUB_OUTPUT
      - name: Get runner version
        id: runner_version
        run: |
          echo version="$(cat ./runner-images/RUNNER_VERSION)" >> $GITHUB_OUTPUT
  runner-images:
    name: Build and push runner images
    needs: get-versions
    uses: ./.github/workflows/reusable-runner-images.yaml
    with:
      meows_version: ${{ needs.get-versions.outputs.meows_version }}
      runner_version: ${{ needs.get-versions.outputs.runner_version }}
      push_image: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
